"use strict";
// This file will be auto-generated by Supabase CLI
// Run: supabase gen types typescript --project-id $NEXT_PUBLIC_SUPABASE_PROJECT_ID --schema public > packages/database/src/types/supabase.ts
Object.defineProperty(exports, "__esModule", { value: true });
//# sourceMappingURL=supabase.js.map